cartas = {
    "espadas": [
        {"id": 1,  "valor": 1,  "nome": "Ás de Espadas",     "cor": "Preto", "naipe": "Espadas", "porcentagem": 10},
        {"id": 2,  "valor": 2,  "nome": "2 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 1},
        {"id": 3,  "valor": 3,  "nome": "3 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 1},
        {"id": 4,  "valor": 4,  "nome": "4 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 1},
        {"id": 5,  "valor": 5,  "nome": "5 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 1},
        {"id": 6,  "valor": 6,  "nome": "6 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 2},
        {"id": 7,  "valor": 7,  "nome": "7 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 3},
        {"id": 8,  "valor": 8,  "nome": "8 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 4},
        {"id": 9,  "valor": 9,  "nome": "9 de Espadas",      "cor": "Preto", "naipe": "Espadas", "porcentagem": 5},
        {"id": 10, "valor": 10, "nome": "10 de Espadas",     "cor": "Preto", "naipe": "Espadas", "porcentagem": 6},
        {"id": 11, "valor": 11, "nome": "Valete de Espadas", "cor": "Preto", "naipe": "Espadas", "porcentagem": 7},
        {"id": 12, "valor": 12, "nome": "Dama de Espadas",   "cor": "Preto", "naipe": "Espadas", "porcentagem": 8},
        {"id": 13, "valor": 13, "nome": "Rei de Espadas",    "cor": "Preto", "naipe": "Espadas", "porcentagem": 9},
    ],
    "paus": [
        {"id": 14, "valor": 1,  "nome": "Ás de Paus",        "cor": "Preto", "naipe": "Paus", "porcentagem": 10},
        {"id": 15, "valor": 2,  "nome": "2 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 1},
        {"id": 16, "valor": 3,  "nome": "3 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 1},
        {"id": 17, "valor": 4,  "nome": "4 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 1},
        {"id": 18, "valor": 5,  "nome": "5 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 1},
        {"id": 19, "valor": 6,  "nome": "6 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 2},
        {"id": 20, "valor": 7,  "nome": "7 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 3},
        {"id": 21, "valor": 8,  "nome": "8 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 4},
        {"id": 22, "valor": 9,  "nome": "9 de Paus",         "cor": "Preto", "naipe": "Paus", "porcentagem": 5},
        {"id": 23, "valor": 10, "nome": "10 de Paus",        "cor": "Preto", "naipe": "Paus", "porcentagem": 6},
        {"id": 24, "valor": 11, "nome": "Valete de Paus",    "cor": "Preto", "naipe": "Paus", "porcentagem": 7},
        {"id": 25, "valor": 12, "nome": "Dama de Paus",      "cor": "Preto", "naipe": "Paus", "porcentagem": 8},
        {"id": 26, "valor": 13, "nome": "Rei de Paus",       "cor": "Preto", "naipe": "Paus", "porcentagem": 9},
    ],
    "copas": [
        {"id": 27, "valor": 1,  "nome": "Ás de Copas",       "cor": "Vermelho", "naipe": "Copas", "porcentagem": 10},
        {"id": 28, "valor": 2,  "nome": "2 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 1},
        {"id": 29, "valor": 3,  "nome": "3 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 1},
        {"id": 30, "valor": 4,  "nome": "4 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 1},
        {"id": 31, "valor": 5,  "nome": "5 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 1},
        {"id": 32, "valor": 6,  "nome": "6 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 2},
        {"id": 33, "valor": 7,  "nome": "7 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 3},
        {"id": 34, "valor": 8,  "nome": "8 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 4},
        {"id": 35, "valor": 9,  "nome": "9 de Copas",        "cor": "Vermelho", "naipe": "Copas", "porcentagem": 5},
        {"id": 36, "valor": 10, "nome": "10 de Copas",       "cor": "Vermelho", "naipe": "Copas", "porcentagem": 6},
        {"id": 37, "valor": 11, "nome": "Valete de Copas",   "cor": "Vermelho", "naipe": "Copas", "porcentagem": 7},
        {"id": 38, "valor": 12, "nome": "Dama de Copas",     "cor": "Vermelho", "naipe": "Copas", "porcentagem": 8},
        {"id": 39, "valor": 13, "nome": "Rei de Copas",      "cor": "Vermelho", "naipe": "Copas", "porcentagem": 9},
    ],
    "ouros": [
        {"id": 40, "valor": 1,  "nome": "Ás de Ouros",       "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 10},
        {"id": 41, "valor": 2,  "nome": "2 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 1},
        {"id": 42, "valor": 3,  "nome": "3 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 1},
        {"id": 43, "valor": 4,  "nome": "4 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 1},
        {"id": 44, "valor": 5,  "nome": "5 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 1},
        {"id": 45, "valor": 6,  "nome": "6 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 2},
        {"id": 46, "valor": 7,  "nome": "7 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 3},
        {"id": 47, "valor": 8,  "nome": "8 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 4},
        {"id": 48, "valor": 9,  "nome": "9 de Ouros",        "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 5},
        {"id": 49, "valor": 10, "nome": "10 de Ouros",       "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 6},
        {"id": 50, "valor": 11, "nome": "Valete de Ouros",   "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 7},
        {"id": 51, "valor": 12, "nome": "Dama de Ouros",     "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 8},
        {"id": 52, "valor": 13, "nome": "Rei de Ouros",      "cor": "Vermelho", "naipe": "Ouros", "porcentagem": 9},
    ]
}